match /var/run, not /run
/run is an alias for /var/run, so creating rules for /run doesn't work:

    # semanage fcontext --add -t foreman_var_run_t /run/foreman.sock
    ValueError: File spec /run/foreman.sock conflicts with equivalency rule '/run /var/run'; Try adding '/var/run/foreman.sock' instead